name: inv-radar
channels:
  - nvidia/label/cuda-12.4.0
  - conda-forge
dependencies:
  - python==3.12
  - pip
  - cuda
  - cuda-toolkit
  - cuda-cudart
  - pip:
    - numpy==1.26.2
    - matplotlib==3.5.1
    - torch==2.3.1
    - torchvision==0.18.1
    - tensorboard==2.17.0
    - slangtorch==1.3.2
    - imageio==2.33.1
    - imageio-ffmpeg==0.4.9
    - trimesh==4.0.5
